name: Generate Tech Debt Health Check Report
#description: 'Generate a report into progress of tech debt initiatives'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-tech-debt-health-check-report:
    runs-on: [ubuntu-latest]
    steps:
#      uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: |
#            ${{ secrets.DEPLOY_KEY_A868_RUNWAY_COMPONENTS_ANDROID }}

      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
        with:
          path: app
          submodules: 'recursive'

      - name: Set report name based on branch
        id: "get_report_name"
        shell: bash
        working-directory: app
        run: |
          branch_name="$(git branch --show-current)"
          echo "## Current branch: $branch_name"
          if [ $branch_name == "android/release/" ]; then
            echo "In a release branch"
            echo "In a release branch again"
            echo "$report_name_suffix='abcd'"
            echo "Report name suffix: $report_name_suffix"
            echo "$report_name=Health check report - $report_name_suffix.md" >> $GITHUB_ENV
          else
            report_name="Health check report - $branch_name.md"
            echo "report_name=$report_name" >> $GITHUB_OUTPUT
          fi
          echo "## report name is: $report_name"

      - name: Run tech debt health check script
        shell: bash
        working-directory: app
        run: |
          ./.github/scripts/tech_debt_health_check.sh
        env:
          FILENAME: ${{ steps.get_report_name.outputs.report_name }}

      - name: 🛒 Checkout wiki
        uses: actions/checkout@v4
        with:
          path: wiki
          repository: ${{github.repository}}.wiki

      - name: Copy health check file to wiki
        run: |
          cp 'app/${{ env.FILENAME }}' 'wiki/${{ env.FILENAME }}'
        env:
          FILENAME: ${{ steps.get_report_name.outputs.report_name }}

      - name: Update Health Check index file
        shell: bash
        working-directory: wiki
        run: |
          ../app/.github/scripts/tech_debt_health_check_index_file_update.sh
        env:
          FILENAME: ${{ steps.get_report_name.outputs.report_name }}

      - name: Commit files
        shell: bash
        run: |
          cd wiki
          git config --global user.email "${GITHUB_USER}@users.noreply.github.com"
          git config --global user.name "${GITHUB_USER}"
          git add .
          git commit -m "Updated the tech debt health check report" --allow-empty
        env:
          GITHUB_USER: ${{ github.actor }}

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki    # specify the wiki repo and push the update..
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          directory: wiki

      - name: 📤 Upload health check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tech-debt-health-check-report
          path: './app/${{ github.REPORT_NAME }}'