name: Generate Tech Debt Health Check Report
#description: 'Generate a report into progress of tech debt initiatives'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-tech-debt-health-check-report:
    runs-on: [ubuntu-latest]
    steps:
#      uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: |
#            ${{ secrets.DEPLOY_KEY_A868_RUNWAY_COMPONENTS_ANDROID }}

      - name: 🛒 Checkout repo
        uses: actions/checkout@v4
        with:
          path: app
          submodules: 'recursive'

      - name: Run tech debt health check script
        shell: bash
        working-directory: app
        run: |
          ./.github/scripts/tech_debt_health_check.sh
        env:
          FILENAME: 'Tech Debt Health Check - master.md'

      - name: 🛒 Checkout wiki
        uses: actions/checkout@v4
        with:
          path: wiki
          repository: ${{github.repository}}.wiki

      - name: Copy health check file to wiki
        run: mkdir -p 'wiki/Health Checks' && cp 'app/Tech Debt Health Check - master.md' 'wiki/Health Checks/Tech Debt Health Check - master.md'

      - name: Commit files
        shell: bash
        run: |
          cd wiki
          git config --global user.email "${GITHUB_USER}@users.noreply.github.com"
          git config --global user.name "${GITHUB_USER}"
          git add .
          git commit -m "Updated the tech debt health check report" --allow-empty
        env:
          GITHUB_USER: ${{ github.actor }}

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki    # specify the wiki repo and push the update..
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          directory: wiki

      - name: 📤 Upload health check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tech-debt-health-check-report
          path: './app/Tech Debt Health Check - master.md'